export function editorconfigTemplate() {
  return [
    "root = true",
    "",
    "[*]",
    "charset = utf-8",
    "end_of_line = lf",
    "indent_style = space",
    "indent_size = 2",
    "insert_final_newline = true",
    "trim_trailing_whitespace = true",
    "",
    "[*.md]",
    "trim_trailing_whitespace = false",
    "",
  ].join("\n");
}

export function gitignoreTemplate() {
  return ["node_modules", "dist", "coverage", "*.log", ".DS_Store", ".env", ".env.*", ""].join(
    "\n",
  );
}

export function gitattributesTemplate() {
  return ["* text=auto eol=lf", ""].join("\n");
}

export function tsconfigTemplate() {
  return (
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "ESNext",
          moduleResolution: "Bundler",
          allowImportingTsExtensions: true,
          strict: true,
          skipLibCheck: true,
          noEmit: true,
        },
        include: ["src"],
      },
      null,
      2,
    ) + "\n"
  );
}

export function srcIndexTemplate() {
  return ["export function hello(name: string) {", "  return `Hello, ${name}`;", "}", ""].join(
    "\n",
  );
}

export function srcVitestTemplate() {
  return [
    'import { describe, expect, it } from "vite-plus/test";',
    'import { hello } from "./index.ts";',
    "",
    'describe("hello", () => {',
    '  it("greets", () => {',
    '    expect(hello("world")).toBe("Hello, world");',
    "  });",
    "});",
    "",
  ].join("\n");
}

export function readmeTemplate(projectName: string) {
  return [`# ${projectName}`, "", "Generated by `frontpl`.", ""].join("\n");
}

function vitePlusLintConfigBlock({ useVitest }: { useVitest: boolean }) {
  return [
    "  lint: oxlint({",
    '    profile: "lib",',
    `    test: "${useVitest ? "vitest" : "none"}",`,
    '    level: "recommended",',
    "    extra: {",
    "      options: {",
    "        typeAware: true,",
    "        typeCheck: true,",
    "      },",
    "    },",
    "  }),",
  ].join("\n");
}

function vitePlusFmtConfigBlock() {
  return [
    "  fmt: {",
    "    useTabs: false,",
    "    indentWidth: 2,",
    "    lineWidth: 100,",
    '    trailingComma: "all",',
    "    semi: true,",
    "    singleQuote: false,",
    '    arrowParens: "always",',
    "  },",
  ].join("\n");
}

export function vitePlusConfigTemplate(opts: {
  useOxlint: boolean;
  useOxfmt: boolean;
  useVitest: boolean;
  useTsdown: boolean;
}) {
  const blocks: string[] = [];

  if (opts.useOxlint) {
    blocks.push(vitePlusLintConfigBlock({ useVitest: opts.useVitest }));
  }

  if (opts.useOxfmt) {
    blocks.push(vitePlusFmtConfigBlock());
  }

  if (opts.useVitest) {
    blocks.push(["  test: {", '    include: ["src/**/*.test.ts"],', "  },"].join("\n"));
  }

  if (opts.useTsdown) {
    blocks.push(
      ["  pack: {", '    entry: ["src/index.ts"],', '    platform: "browser",', "  },"].join("\n"),
    );
  }

  return [
    'import { defineConfig } from "vite-plus";',
    ...(opts.useOxlint ? ['import { oxlint } from "@kingsword/lint-config/config";'] : []),
    "",
    "export default defineConfig({",
    blocks.join("\n"),
    "});",
    "",
  ].join("\n");
}

export function mergeVitePlusConfigTemplate(
  current: string,
  opts: {
    useOxlint: boolean;
    useOxfmt: boolean;
    useVitest: boolean;
    useTsdown: boolean;
  },
) {
  if (!findDefineConfigObjectPattern(current)) {
    return current.trim().length > 0 ? `${current.trimEnd()}\n` : vitePlusConfigTemplate(opts);
  }

  const blocks: string[] = [];
  if (opts.useOxlint && !hasVitePlusConfigProperty(current, "lint")) {
    blocks.push(vitePlusLintConfigBlock({ useVitest: opts.useVitest }));
  }
  if (opts.useOxfmt && !hasVitePlusConfigProperty(current, "fmt")) {
    blocks.push(vitePlusFmtConfigBlock());
  }
  if (opts.useVitest && !hasVitePlusConfigProperty(current, "test")) {
    blocks.push(["  test: {", '    include: ["src/**/*.test.ts"],', "  },"].join("\n"));
  }
  if (opts.useTsdown && !hasVitePlusConfigProperty(current, "pack")) {
    blocks.push(
      ["  pack: {", '    entry: ["src/index.ts"],', '    platform: "browser",', "  },"].join("\n"),
    );
  }

  let merged = current.trimEnd();
  merged = ensureVitePlusDefineConfigImport(merged);
  if (opts.useOxlint) merged = ensureOxlintPresetImport(merged);
  if (blocks.length > 0) {
    const { index, value } = findDefineConfigObjectPattern(merged)!;
    merged = `${merged.slice(0, index + value.length)}\n${blocks.join("\n")}${merged.slice(index + value.length)}`;
  }
  return `${merged}\n`;
}

function findDefineConfigObjectPattern(config: string) {
  const directConfig = /defineConfig\(\s*\{/;
  const directMatch = directConfig.exec(config);
  if (directMatch) return { index: directMatch.index, value: directMatch[0] };

  const arrowObjectConfig =
    /defineConfig\(\s*(?:async\s+)?(?:\([^)]*\)|[A-Za-z_$][\w$]*)\s*=>\s*\(\s*\{/;
  const arrowObjectMatch = arrowObjectConfig.exec(config);
  if (arrowObjectMatch) return { index: arrowObjectMatch.index, value: arrowObjectMatch[0] };

  return;
}

function hasVitePlusConfigProperty(config: string, property: string) {
  return new RegExp(`^\\s{2}${property}:`, "m").test(config);
}

function ensureVitePlusDefineConfigImport(config: string) {
  const viteImport = /(import\s+\{[^}]*\bdefineConfig\b[^}]*\}\s+from\s+)["']vite["'];/;
  if (viteImport.test(config)) return config.replace(viteImport, '$1"vite-plus";');
  if (/from\s+["']vite-plus["']/.test(config)) return config;
  return ['import { defineConfig } from "vite-plus";', config].join("\n");
}

function ensureOxlintPresetImport(config: string) {
  if (/from\s+["']@kingsword\/lint-config\/config["']/.test(config)) return config;
  const lines = config.split("\n");
  let lastImportIndex = -1;
  for (let index = 0; index < lines.length; index += 1) {
    if (lines[index]?.startsWith("import ")) lastImportIndex = index;
  }
  lines.splice(lastImportIndex + 1, 0, 'import { oxlint } from "@kingsword/lint-config/config";');
  return lines.join("\n");
}

type LintAndFormatTemplateOptions = {
  useOxlint: boolean;
  oxlintVersion?: string;
  oxlintTsgolintVersion?: string;
  kingswordLintConfigVersion?: string;
  useOxfmt: boolean;
  oxfmtVersion?: string;
  vitePlusVersion?: string;
};

function usesVitePlusToolchain(opts: {
  useOxlint: boolean;
  useOxfmt: boolean;
  useVitest?: boolean;
  useTsdown?: boolean;
}) {
  return opts.useOxlint || opts.useOxfmt || opts.useVitest === true || opts.useTsdown === true;
}

function applyLintAndFormatScripts(
  scripts: Record<string, string>,
  opts: Pick<LintAndFormatTemplateOptions, "useOxlint" | "useOxfmt">,
) {
  if (opts.useOxlint) {
    scripts.lint = "vp lint";
    scripts["lint:fix"] = "vp lint --fix";
  }

  if (opts.useOxfmt) {
    scripts.format = "vp fmt";
    scripts["format:check"] = "vp fmt --check";
  }
}

function applyLintAndFormatDependencies(
  devDependencies: Record<string, string>,
  opts: LintAndFormatTemplateOptions,
) {
  if (usesVitePlusToolchain(opts) && opts.vitePlusVersion) {
    devDependencies["vite-plus"] = opts.vitePlusVersion;
  }

  if (opts.useOxlint) {
    if (opts.oxlintVersion) devDependencies.oxlint = opts.oxlintVersion;
    if (opts.kingswordLintConfigVersion) {
      devDependencies["@kingsword/lint-config"] = opts.kingswordLintConfigVersion;
    }
  }
}

export function packageJsonTemplate(opts: {
  name: string;
  packageManager: string;
  typescriptVersion: string;
  useOxlint: boolean;
  includeTypecheckWithoutOxlint?: boolean;
  oxlintVersion?: string;
  oxlintTsgolintVersion?: string;
  kingswordLintConfigVersion?: string;
  useOxfmt: boolean;
  oxfmtVersion?: string;
  vitePlusVersion?: string;
  useVitest: boolean;
  vitestVersion?: string;
  useTsdown: boolean;
  tsdownVersion?: string;
}) {
  const scripts: Record<string, string> = {};

  if (!opts.useOxlint && opts.includeTypecheckWithoutOxlint !== false) {
    scripts.typecheck = "tsc --noEmit";
  }

  applyLintAndFormatScripts(scripts, opts);

  if (opts.useVitest) {
    scripts.test = "vp test";
  }

  if (opts.useTsdown) {
    scripts.build = "vp pack";
  }

  const devDependencies: Record<string, string> = {
    typescript: opts.typescriptVersion,
  };

  applyLintAndFormatDependencies(devDependencies, opts);

  return (
    JSON.stringify(
      {
        name: opts.name,
        version: "0.0.0",
        private: true,
        type: "module",
        scripts,
        devDependencies,
        packageManager: opts.packageManager,
      },
      null,
      2,
    ) + "\n"
  );
}

export function workspaceRootPackageJsonTemplate(opts: {
  name: string;
  packageManager: string;
  useOxlint: boolean;
  oxlintVersion?: string;
  oxlintTsgolintVersion?: string;
  kingswordLintConfigVersion?: string;
  useOxfmt: boolean;
  oxfmtVersion?: string;
  vitePlusVersion?: string;
  useVitest: boolean;
  useTsdown: boolean;
}) {
  const scripts: Record<string, string> = {};
  applyLintAndFormatScripts(scripts, opts);

  if (opts.useVitest) {
    scripts.test = "vp run -r test";
  }

  if (opts.useTsdown) {
    scripts.build = "vp run -r build";
  }

  const devDependencies: Record<string, string> = {};
  applyLintAndFormatDependencies(devDependencies, opts);

  const manifest: {
    name: string;
    private: boolean;
    type: string;
    packageManager: string;
    scripts?: Record<string, string>;
    devDependencies?: Record<string, string>;
  } = {
    name: opts.name,
    private: true,
    type: "module",
    packageManager: opts.packageManager,
  };

  if (Object.keys(scripts).length > 0) {
    manifest.scripts = scripts;
  }

  if (Object.keys(devDependencies).length > 0) {
    manifest.devDependencies = devDependencies;
  }

  return JSON.stringify(manifest, null, 2) + "\n";
}

const DEFAULT_WORKFLOWS_REF = "7320d30bcd47cee17cc2d8d28250ba1ab1f742b8";
const DEFAULT_WORKFLOWS_VERSION = "v1.0.3";

function resolveWorkflowsPin(opts: { workflowsRef?: string; workflowsVersion?: string }) {
  const ref = opts.workflowsRef?.trim() || DEFAULT_WORKFLOWS_REF;
  const version =
    opts.workflowsVersion?.trim() || (opts.workflowsRef ? undefined : DEFAULT_WORKFLOWS_VERSION);

  return {
    ref,
    versionComment: version ? ` # ${version}` : "",
  };
}

export function githubCliCiWorkflowTemplate(opts: {
  packageManager: "npm" | "pnpm" | "yarn" | "bun" | "deno";
  nodeVersion: number;
  workingDirectory: string;
  runLint: boolean;
  runFormatCheck: boolean;
  runTests: boolean;
  installCommand?: string;
  lintCommand?: string;
  formatCheckCommand?: string;
  testCommand?: string;
  workflowsRef?: string;
  workflowsVersion?: string;
}) {
  const { ref, versionComment } = resolveWorkflowsPin(opts);
  const installCommand = opts.installCommand?.trim();
  const lintCommand = opts.lintCommand?.trim();
  const formatCheckCommand = opts.formatCheckCommand?.trim();
  const testCommand = opts.testCommand?.trim();
  return [
    "name: CI",
    "",
    "on:",
    "  push:",
    "    branches: [main]",
    "  pull_request:",
    "    branches: [main]",
    "",
    "jobs:",
    "  ci:",
    `    uses: kingsword09/workflows/.github/workflows/cli-ci.yml@${ref}${versionComment}`,
    "    with:",
    `      packageManager: ${opts.packageManager}`,
    `      nodeVersion: ${opts.nodeVersion}`,
    `      workingDirectory: ${opts.workingDirectory}`,
    `      runLint: ${opts.runLint}`,
    `      runFormatCheck: ${opts.runFormatCheck}`,
    `      runTests: ${opts.runTests}`,
    ...(installCommand ? [`      installCommand: ${yamlString(installCommand)}`] : []),
    ...(lintCommand ? [`      lintCommand: ${yamlString(lintCommand)}`] : []),
    ...(formatCheckCommand ? [`      formatCheckCommand: ${yamlString(formatCheckCommand)}`] : []),
    ...(testCommand ? [`      testCommand: ${yamlString(testCommand)}`] : []),
    "",
  ].join("\n");
}

export function githubCliReleaseWorkflowTemplate(opts: {
  packageManager: "npm" | "pnpm" | "yarn" | "bun" | "deno";
  nodeVersion: number;
  workingDirectory: string;
  trustedPublishing?: boolean;
  workflowsRef?: string;
  workflowsVersion?: string;
}) {
  const { ref, versionComment } = resolveWorkflowsPin(opts);
  const trustedPublishing = opts.trustedPublishing;
  const needsNpmToken = opts.packageManager !== "deno" && trustedPublishing === false;
  return [
    "name: Release",
    "",
    "on:",
    "  push:",
    "    branches: [main]",
    "",
    "jobs:",
    "  release:",
    "    permissions:",
    "      contents: write",
    "      id-token: write",
    `    uses: kingsword09/workflows/.github/workflows/cli-release.yml@${ref}${versionComment}`,
    "    with:",
    `      packageManager: ${opts.packageManager}`,
    `      nodeVersion: ${opts.nodeVersion}`,
    `      workingDirectory: ${opts.workingDirectory}`,
    ...(trustedPublishing === undefined ? [] : [`      trustedPublishing: ${trustedPublishing}`]),
    ...(needsNpmToken ? ["    secrets:", "      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}"] : []),
    "",
  ].join("\n");
}

export function githubCliReleaseTagWorkflowTemplate(opts: {
  packageManager: "npm" | "pnpm" | "yarn" | "bun" | "deno";
  nodeVersion: number;
  workingDirectory: string;
  trustedPublishing?: boolean;
  workflowsRef?: string;
  workflowsVersion?: string;
}) {
  const { ref, versionComment } = resolveWorkflowsPin(opts);
  const trustedPublishing = opts.trustedPublishing;
  const needsNpmToken = opts.packageManager !== "deno" && trustedPublishing === false;
  return [
    "name: Release",
    "",
    "on:",
    "  push:",
    "    tags: [v*.*.*]",
    "",
    "jobs:",
    "  release:",
    "    permissions:",
    "      contents: write",
    "      id-token: write",
    `    uses: kingsword09/workflows/.github/workflows/cli-release-tag.yml@${ref}${versionComment}`,
    "    with:",
    `      packageManager: ${opts.packageManager}`,
    `      nodeVersion: ${opts.nodeVersion}`,
    `      workingDirectory: ${opts.workingDirectory}`,
    ...(trustedPublishing === undefined ? [] : [`      trustedPublishing: ${trustedPublishing}`]),
    ...(needsNpmToken ? ["    secrets:", "      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}"] : []),
    "",
  ].join("\n");
}

export function githubCliReleaseBothWorkflowTemplate(opts: {
  packageManager: "npm" | "pnpm" | "yarn" | "bun" | "deno";
  nodeVersion: number;
  workingDirectory: string;
  trustedPublishing?: boolean;
  workflowsRef?: string;
  workflowsVersion?: string;
}) {
  const { ref, versionComment } = resolveWorkflowsPin(opts);
  const trustedPublishing = opts.trustedPublishing;
  const needsNpmToken = opts.packageManager !== "deno" && trustedPublishing === false;
  return [
    "name: Release",
    "",
    "on:",
    "  push:",
    "    branches: [main]",
    "    tags: [v*.*.*]",
    "",
    "jobs:",
    "  release_tag:",
    "    if: startsWith(github.ref, 'refs/tags/')",
    "    permissions:",
    "      contents: write",
    "      id-token: write",
    `    uses: kingsword09/workflows/.github/workflows/cli-release-tag.yml@${ref}${versionComment}`,
    "    with:",
    `      packageManager: ${opts.packageManager}`,
    `      nodeVersion: ${opts.nodeVersion}`,
    `      workingDirectory: ${opts.workingDirectory}`,
    ...(trustedPublishing === undefined ? [] : [`      trustedPublishing: ${trustedPublishing}`]),
    ...(needsNpmToken ? ["    secrets:", "      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}"] : []),
    "",
    "  release_commit:",
    "    if: startsWith(github.ref, 'refs/heads/')",
    "    permissions:",
    "      contents: write",
    "      id-token: write",
    `    uses: kingsword09/workflows/.github/workflows/cli-release.yml@${ref}${versionComment}`,
    "    with:",
    `      packageManager: ${opts.packageManager}`,
    `      nodeVersion: ${opts.nodeVersion}`,
    `      workingDirectory: ${opts.workingDirectory}`,
    ...(trustedPublishing === undefined ? [] : [`      trustedPublishing: ${trustedPublishing}`]),
    ...(needsNpmToken ? ["    secrets:", "      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}"] : []),
    "",
  ].join("\n");
}

function toDependabotDirectory(workingDirectory: string): string {
  const normalized = workingDirectory.trim();
  if (!normalized || normalized === ".") return "/";
  return normalized.startsWith("/") ? normalized : `/${normalized}`;
}

function resolveDependabotPackageEcosystem(
  packageManager: "npm" | "pnpm" | "yarn" | "bun" | "deno",
): "npm" | undefined {
  if (packageManager === "deno") return;
  return "npm";
}

export function githubDependabotTemplate(opts: {
  packageManager: "npm" | "pnpm" | "yarn" | "bun" | "deno";
  workingDirectory: string;
}) {
  const packageEcosystem = resolveDependabotPackageEcosystem(opts.packageManager);
  const directory = toDependabotDirectory(opts.workingDirectory);

  return [
    "version: 2",
    "updates:",
    ...(packageEcosystem
      ? [
          `  - package-ecosystem: "${packageEcosystem}"`,
          `    directory: "${directory}"`,
          "    schedule:",
          '      interval: "weekly"',
          '      day: "monday"',
          '      time: "03:00"',
          '      timezone: "America/Los_Angeles"',
          "    open-pull-requests-limit: 10",
          "    groups:",
          "      dependencies:",
          "        patterns:",
          '          - "*"',
          "    labels:",
          '      - "dependencies"',
          "",
        ]
      : []),
    '  - package-ecosystem: "github-actions"',
    '    directory: "/"',
    "    schedule:",
    '      interval: "weekly"',
    '      day: "monday"',
    '      time: "03:00"',
    '      timezone: "America/Los_Angeles"',
    "    open-pull-requests-limit: 10",
    "    groups:",
    "      github-actions:",
    "        patterns:",
    '          - "*"',
    "    labels:",
    '      - "dependencies"',
    '      - "github-actions"',
    "",
  ].join("\n");
}

function yamlString(value: string) {
  return JSON.stringify(value);
}
